spring.application.name=bank-batch-migration

spring.datasource.url=jdbc:mysql://localhost:3306/bank_batch_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true
spring.batch.job.name=estadosCuentaAnualesJob

spring.sql.init.mode=always